/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUICollection2;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author TUF GAMING
 */
public class GUICollection2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    DefaultListModel<String> dlm;
    List<String> items = new ArrayList<>();
    Set<String> itemsSET = new HashSet<>();
    Map<Integer, String> itemsMAP = new HashMap<>();
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu"};
    
    public GUICollection2() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jList1.setModel(dlm);
        
        for (String data : datas){
            dlm.addElement(data);
            updateJumDataTersimpan();
        }
    }
    private void updateJumDataTersimpan() {
        JumData.setText(
        "Data Tersimpan = "+ items.size());
        JumData2.setText(
        "Data Tersimpan = "+ itemsSET.size());
        JumData3.setText(
        "Data Tersimpan = "+ itemsMAP.size());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        TEKS = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        DEL = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        INPUT = new javax.swing.JButton();
        JumData = new javax.swing.JLabel();
        SAVELIST = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SAVESET = new javax.swing.JButton();
        InpotDataSET = new javax.swing.JButton();
        SAVEMAP = new javax.swing.JButton();
        InpotDataMAP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JumData2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JumData3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Tulis Data :");

        TEKS.setText("ITEM1");

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        DEL.setText("DEL");
        DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELActionPerformed(evt);
            }
        });

        CLEAR.setText("CLEAR ALL");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        INPUT.setText("InpotDataLIST");
        INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUTActionPerformed(evt);
            }
        });

        JumData.setText("jLabel2");

        SAVELIST.setText("SAVELIST");
        SAVELIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVELISTActionPerformed(evt);
            }
        });

        jLabel2.setText("<-- Save to LIST");

        SAVESET.setText("SAVESET");
        SAVESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVESETActionPerformed(evt);
            }
        });

        InpotDataSET.setText("InpotDataSET");
        InpotDataSET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InpotDataSETActionPerformed(evt);
            }
        });

        SAVEMAP.setText("SAVEMAP");
        SAVEMAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEMAPActionPerformed(evt);
            }
        });

        InpotDataMAP.setText("InpotDataMAP");
        InpotDataMAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InpotDataMAPActionPerformed(evt);
            }
        });

        jLabel3.setText("<-- Save to SET");

        JumData2.setText("jLabel4");

        jLabel5.setText("<-- Save to MAP");

        JumData3.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TEKS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(INPUT)
                                    .addComponent(SAVELIST)
                                    .addComponent(SAVESET)
                                    .addComponent(InpotDataSET)
                                    .addComponent(SAVEMAP)
                                    .addComponent(InpotDataMAP))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JumData3)
                                    .addComponent(jLabel5)
                                    .addComponent(JumData2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(JumData)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CLEAR)
                        .addGap(18, 18, 18)
                        .addComponent(ADD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DEL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SAVELIST)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INPUT)
                            .addComponent(JumData))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SAVESET)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InpotDataSET)
                            .addComponent(JumData2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SAVEMAP)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InpotDataMAP)
                            .addComponent(JumData3))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TEKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DEL)
                    .addComponent(CLEAR)
                    .addComponent(ADD)
                    .addComponent(UPDATE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUTActionPerformed

    for (String item : items) {
    dlm.addElement(item);
}
    }//GEN-LAST:event_INPUTActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        dlm.addElement(TEKS.getText());
        TEKS.setText("");
    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        int index = jList1.getSelectedIndex();
        String selected = TEKS.getText();
        dlm.setElementAt(selected, index);
        TEKS.setText("");       
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELActionPerformed
        int index = jList1.getSelectedIndex();
        dlm.removeElementAt(index);
        TEKS.setText(""); 
    }//GEN-LAST:event_DELActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        dlm.clear();
    }//GEN-LAST:event_CLEARActionPerformed

    private void SAVELISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVELISTActionPerformed
        if (!items.isEmpty()){
            items.clear();
        }
        for (int i = 0;i < dlm.getSize();i++){
            items.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpan();
    }//GEN-LAST:event_SAVELISTActionPerformed

    private void SAVESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVESETActionPerformed
        if (!itemsSET.isEmpty()){
            itemsSET.clear();
        }
        for (int i = 0;i < dlm.getSize();i++){
            itemsSET.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpan();
    }//GEN-LAST:event_SAVESETActionPerformed

    private void SAVEMAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEMAPActionPerformed
        if (!itemsMAP.isEmpty()){
            itemsMAP.clear();
        }
        for (int i = 0;i < dlm.getSize();i++){
            itemsMAP.put(i, dlm.getElementAt(i));
        }
        updateJumDataTersimpan();
    }//GEN-LAST:event_SAVEMAPActionPerformed

    private void InpotDataSETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InpotDataSETActionPerformed
    for (String item : itemsSET) {
    dlm.addElement(item);
}
    }//GEN-LAST:event_InpotDataSETActionPerformed

    private void InpotDataMAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InpotDataMAPActionPerformed
    for (Integer key : itemsMAP.keySet()) {
    dlm.addElement(itemsMAP.get(key));
}
    }//GEN-LAST:event_InpotDataMAPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICollection2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICollection2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICollection2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICollection2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICollection2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DEL;
    private javax.swing.JButton INPUT;
    private javax.swing.JButton InpotDataMAP;
    private javax.swing.JButton InpotDataSET;
    private javax.swing.JLabel JumData;
    private javax.swing.JLabel JumData2;
    private javax.swing.JLabel JumData3;
    private javax.swing.JButton SAVELIST;
    private javax.swing.JButton SAVEMAP;
    private javax.swing.JButton SAVESET;
    private javax.swing.JTextField TEKS;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
